config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'
  match 'auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

  get '/shoes/expensive', to: 'shoes#expensive', as: 'expensive_shoe'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :shoes

  resources :brands do 
    resources :shoes, shallow: true
  end

end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes, dependent: :destroy
    has_many :users, through: :shoes
    validates :name, presence: true, uniqueness: { case_sensitive: false }

    # accepts_nested_attributes_for :shoes, reject_if: proc {|attr| attr['color'].blank? || attr['price'].blank?}
    
    # def shoes_attributes=(attr)
    #     attr.each do | k, v |
    #         User.find_by(session[:user_id]).shoes.create(v) if !v[:price].blank?
    #     end 
    # end 
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :set_brand, only: [:show, :update, :edit, :destroy]

    def new
        @brand = Brand.new
    end 

    def show
        
    end 
    
    def index
        @brands = Brand.all 
    end 

    def create
        @brand = Brand.new(brand_params)
        if @brand.save
            redirect_to brand_path(@brand)
        else
            render :new
        end
    end 

    def edit
       
    end

    def update
        @brand.update(brand_params)
        redirect_to brand_path(brand)
    end 

    def destroy
        @brand.destroy
        redirect_to brands_path
    end 


    private

    def brand_params
        params.require(:brand).permit(:name, :owner, shoes_attributes: [:price, :price_confirmation, :color, :limited_edition])
    end 

    def set_brand 
        @brand = Brand.find_by(id: params[:id])
    end 
    
end

app/views/brands/_fields.html.erb
<%= f.label :name %>
<%= f.text_field :name %><br>
<%= f.label :name, "Owner" %>
<%= f.text_field :owner %>

app/views/brands/edit.html.erb
<h2>Edit Brand</h2>

<%= form_for(@brand) do |f| %>
    <%= render partial: 'fields', locals: {f: f} %>
    <%= f.submit %>
<% end %>

app/views/brands/index.html.erb
<h1>All the Brands </h1>
<% @brands.each do |brand|  %>
    <div>
        <%= link_to(brand.name, brand_path(brand) )   %>
    </div>
<% end %><br>
<%= link_to "Create Brand", new_brand_path %>

app/views/brands/new.html.erb
<h1>Add a New Brand</h1>

<%= render partial: 'layouts/errors', locals: {object: @brand} %>

<%= form_with model: @brand, local: true do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :name, "Owner" %>
  <%= f.text_field :owner %>

  <%= f.submit  %>
<% end %>

app/views/brands/show.html.erb
<h1><%= @brand.name%> - Owned By <%= @brand.owner %> </h1>
<%= logos %><br>
<%= link_to('Delete Brand', brand_path(@brand), method: 'delete') %>

<%= render @brand.shoes %>
<% if @brand %>
<%= link_to "Create a shoe", new_brand_shoe_path(@brand) %>
<% end %>