config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'
  match 'auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

  get '/shoes/expensive', to: 'shoes#expensive', as: 'expensive_shoe'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :shoes

  resources :brands do 
    resources :shoes, shallow: true
  end

end

app/models/shoe.rb
class Shoe < ApplicationRecord
    validates :price, :color, presence: true
    validates :price, numericality: { greater_than: 0 }
    # validates :brand, uniqueness: { scope: [:price, :color], message: 'already has that price & color combo' }
    validates :price, confirmation: true
    # validates :price_confirmation, presence: true
    # validates :color, two_word: true
    belongs_to :brand 
    belongs_to :user
    scope :ordered_by_price, -> { order(price: :desc) }
    scope :less_pricey, -> (price) { where('price < ?', price)}
    # accepts_nested_attributes_for :brand

    def brand_attributes=(attr)
        if !attr[:name].blank?
            self.brand = Brand.find_or_create_by(name: attr[:name], owner: attr[:owner])
        end 
    end 

    # def self.ordered_by_price
    #     #self.all.sort_by{|shoe| shoe.price}.last ##loads all records into RAM, then sorts
    #     self.order(price: :desc) ##database handles sorting
    # end

    def brand_and_color
        "#{self.brand.name} - #{self.color}"
    end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
    # layout 'shoe'
    before_action :find_shoe, :redirect_if_not_owner, only: [:show, :update, :edit, :destroy]

    def index
        if params[:brand_id] && @brand = Brand.find_by_id(params[:brand_id])
            @shoes = @brand.shoes
        else
            @shoes = Shoe.ordered_by_price.less_pricey(80)
        end 
    end

    def show
        
    end

    def new 
        byebug
        if params[:brand_id] && @brand = Brand.find_by_id(params[:brand_id])
            @shoe = @brand.shoes.build  
        else
            @shoe = Shoe.new
            @shoe.build_brand
        end 
    end 

    def create
        
        @shoe = current_user.shoes.build(shoe_params)
       byebug
        if @shoe.save
            redirect_to shoe_path(@shoe)
        else
            @brand = Brand.find_by_id(params[:brand_id]) if params[:brand_id] != ""
            render :new
        end 
    end 

    def edit
    
    end 

    def update 
      
        @shoe.update(shoe_params)
        redirect_to shoe_path(@shoe)
    end 

    def destroy 
        
        shoe.destroy
        redirect_to shoes_path

    end 


    def expensive
        @shoe = Shoe.ordered_by_price.first
    end

    private

    def shoe_params
        params[:shoe][:price_confirmation] = params[:shoe][:price_confirmation].to_f
        params.require(:shoe).permit(:brand_id, :price, :price_confirmation, :color, :limited_edition, brand_attributes: [:name, :owner])
    end 

    def update_params
        params.require(:shoe).permit(:color, :price, :color)
    end 
    
    def find_shoe
        @shoe = Shoe.find(params[:id])
    end 

    def redirect_if_not_owner
        if @shoe.user != current_user
            redirect_to user_path(current_user), alert: "You can't edit this shoe!"
        end
    end

end

app/helpers/shoes_helper.rb
module ShoesHelper

    def display_limited_edition
        if @shoe.limited_edition
            content_tag(:h3, "Limited Edition")
        else
            content_tag(:h4, "Ordinary" )
        end
    end

    def display_header
        if @brand 
            tag.h2("All the #{@brand.name} Shoes")
        else
            tag.h1("All the Shoes")
        end 
    end 

    def display_brand_fields(t)
        if params[:brand_id]
            t.hidden_field :brand_id
        else
            render partial: 'brand_select', locals: {f: t}
        end 
    end 

    def display_nested_header
        if params[:brand_id]
            "Create a new #{@brand.name} shoe"
        else
            "Create New Shoe"
        end 

    end 
end

app/views/shoes/_brand_select.html.erb
<%= f.label :brand, "Brand:" %>
    <%= f.collection_select :brand_id, Brand.all, :id, :name, prompt: true %><br><br>
    <%= f.fields_for :brand do |b| %>
      <%= render partial: 'brands/fields', locals: {f: b} %>
    <% end %><br><br>

app/views/shoes/_form.html.erb
<%= render partial: 'layouts/errors', locals: { object: @shoe } %>
<%= form_with(model: @shoe) do |f|%>
   <%= display_brand_fields(f) %>
    <%= f.label :price, "Price:" %>
    <%= f.number_field :price, min: 0, step: 0.01 %><br><br>
    <%= f.label :price, "Price Confirmation:" %>
    <%= f.number_field :price_confirmation, min: 0, step: 0.01 %><br><br>
    <%= f.label :color, "Color:"%>
    <%= f.text_field :color  %><br><br>
    <%= f.label :limited_edition, "Limited Edition:" %>
    <%= f.check_box :limited_edition %>
    <br><br>

    <%= f.submit %>
<% end %>

app/views/shoes/_shoe.html.erb
<h3>
    <%= link_to(shoe.brand_and_color, shoe_path(shoe))%> -
    <%= number_to_currency(shoe.price) %>
</h3>

app/views/shoes/edit.html.erb
<h1>Edit Shoe</h1>
<%= render partial: 'layouts/errors', locals: { object: @shoe } %>

<%= render 'form' %>

app/views/shoes/expensive.html.erb
<h1>Most Expensive Shoe</h1>

<h2> <%= link_to(@shoe.brand_and_color, shoe_path(@shoe))   %></h2>
<h3><%= number_to_currency(@shoe.price) %></h3>

app/views/shoes/index.html.erb
<%= flash[:alert] %>
<%= display_header %>
<%= render partial: 'shoe', collection: @shoes  %> 
<% if @brand %>
    <%= link_to "create a new shoes for this brand", new_brand_shoe_path(@brand) %>
    <% else %>
<%= link_to("Create Shoe", new_shoe_path )%>
<% end %>

app/views/shoes/new.html.erb
<%= display_nested_header %>
<%= render 'form' %>

app/views/shoes/show.html.erb
<%= display_limited_edition %>
<%= render  @shoe %>

<%= link_to('edit shoe', edit_shoe_path(@shoe)) %>

<%= link_to('delete shoe', shoe_path(@shoe), method: 'delete') %>