config/routes.rb
Rails.application.routes.draw do
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#welcome'
  match 'auth/:provider/callback', to: 'sessions#omniauth', via: [:get, :post]

  get '/shoes/expensive', to: 'shoes#expensive', as: 'expensive_shoe'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :shoes

  resources :brands do 
    resources :shoes, shallow: true
  end

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this brand from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_logged_in.html.erb
<%= link_to("All Shoes", shoes_path )%> |
<%= link_to("All Brands", brands_path) %> |
<%= link_to("Most Expensive Shoe", expensive_shoe_path )%> |
<%= link_to("Logout", '/logout', method: :delete) %>

app/views/layouts/_logged_out.html.erb
<%= link_to("Login with Google", '/auth/google_oauth2', method: :post) %> |
<%= link_to("Login with Github", '/auth/github', method: :post) %> |

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoeCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div>
      <%= render_nav_bar %>
    </div>
    <% if flash[:alert] %>
      <div class="field_with_errors"><%= flash[:alert] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shoe.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoeCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to("All Brands", brands_path )%> |
    <%= link_to("All Shoes", shoes_path )%> |
    <%= link_to("Most Expensive Shoe", expensive_shoe_path )%> |
    <%= link_to("New Shoe", new_shoe_path )%>
    <h2>In the Shoes World</h2>
    <%= yield %>
  </body>
</html>